name: Build & Test Docker App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t hello-docker .

      - name: Run tests
        run: |
          docker run --name test-container hello-docker &
          sleep 5
          docker exec test-container pytest test_app.py
          docker stop test-container
